#!/usr/bin/env python3
"""Build the self-contained viewer from the validated rendering map snapshot."""
import json
from pathlib import Path

repo = Path(__file__).resolve().parents[1]
folder = repo / 'docs/research/skyrim-render-map'
read = lambda name: json.loads((folder/name).read_text())
coverage = read('coverage.json')
frame = read('frame-topology.json')
inputs = read('input-contracts.json')
shaders = read('shader-inventory.json')
connections = read('native-image-space-connections.json')
arithmetic = read('image-space-arithmetic.json')
content_mods = read('mod-content-rendering.json')
hook_mods = read('mod-rendering-hooks.json')
data = dict(coverage={k:v for k,v in coverage.items() if k in ['target_sha256','package','embedded','native_aggregate','input_coverage','image_space_connections','image_space_arithmetic','mod_evidence']},
            graph=frame['graph'], api=frame['api_boundaries'], stages=frame['coverage_matrix'],
            contracts=inputs['contracts'], statuses=inputs['statuses'], groups=shaders['groups'],
            helpers=[dict(offset=h['manager_field_offset'],constructor=h['constructor_va'],render=h['render_va'],
                          fields=[dict(offset=b['field_offset'],slot=b['effect_slot'],group=b['group_id'],label=b['native_loader_label']) for b in h['bindings']]) for h in connections['helper_objects']],
            guard_notes=connections['guards_and_state'], transfers=connections['curated_transfers'],
            hdr={k:v for k,v in connections['hdr_parameter_connection'].items() if k in ['group_id','native_loader_label','selected_effect_slot','source_pointer','byte_count','parameter_channel','hdr_child_index','open']},
            compute={k:v for k,v in connections['compute_dispatch'].items() if k in ['owner_method_va','native_binding_helper','api_calls','open']},
            arithmetic_families=arithmetic['readable_contracts'],
            content_sources=[{k:v for k,v in s.items() if k in ['id','title','url','page_version','page_last_updated_display']} for s in content_mods['source_pins']],
            content_findings=[{k:v for k,v in f.items() if k in ['id','claim','scope','primary_source_url','unproved','query_ids']} for f in content_mods['findings']],
            source_repos=[{k:v for k,v in r.items() if k in ['id','url','commit','branch_at_fetch']} for r in hook_mods['repository_pins']],
            interventions=[{k:v for k,v in i.items() if k in ['id','title','behavior','scheduling','existing_input_domains','next_native_query_ids','source_anchors','limits']} for i in hook_mods['interventions']],
            source_anchors={a['id']:dict(description=a['description'],url=a['url']) for a in hook_mods['source_anchors']},
            source_conflicts=hook_mods['source_contradictions_and_attribution_gaps'])
if data['coverage']['native_aggregate']:
    data['coverage']['native_aggregate']={k:v for k,v in data['coverage']['native_aggregate'].items() if k not in ['queries']}
for group in data['groups']:
    group.pop('stages',None)
payload=json.dumps(data,separators=(',',':')).replace('</','<\\/')
html='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{font-family:var(--font-sans,system-ui,sans-serif);color:var(--foreground,#d9e1e9)}*{box-sizing:border-box}body{margin:0}p{line-height:1.55;margin:0 0 14px}small,.muted{color:var(--muted-foreground,#8e9ba9)}code{font-family:var(--font-mono,ui-monospace,monospace);font-size:.85em;overflow-wrap:anywhere}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.stat,.panel{padding:16px;background:var(--card,#232930);border-radius:var(--radius,9px)}.stat b{display:block;font-size:25px;margin-bottom:5px}.stat span{font-size:12px;color:var(--muted-foreground,#9ba6b3)}nav{display:flex;flex-wrap:wrap;gap:7px;margin:16px 0}button,input,select{font:inherit;color:inherit;background:var(--secondary,#272e35);border:1px solid var(--border,#3b4551);border-radius:6px;padding:8px 10px}button{cursor:pointer}button.active{background:var(--accent-surface,#183c49);color:var(--accent-surface-foreground,#96d8e8);border-color:var(--accent,#59c9da)}input,select{width:100%;margin:0 0 14px}.tab[hidden]{display:none}h3{font-size:16px;font-weight:600;margin:0 0 9px}.edge{padding:13px 0;border-top:1px solid var(--border,#3b4551)}.edge:first-child{border:0;padding-top:0}.edge button{margin:6px 0;text-align:left;width:100%}.tag{display:inline-block;border:1px solid var(--border,#414d59);border-radius:12px;font-size:11px;padding:3px 8px;line-height:1.4}.tag.open{color:var(--warning,#edbb73)}.tag.static{color:var(--info,#84bfd8)}details{border-top:1px solid var(--border,#3b4551);padding:12px 0}summary{cursor:pointer;line-height:1.45;font-size:14px}summary code{color:var(--muted-foreground,#a4b6c4)}details p{font-size:13px;margin:10px 0}details .edge{font-size:13px}.scroll{max-height:560px;overflow:auto;padding-right:4px}ul{padding-left:20px;line-height:1.5}li{margin:7px 0}.note{font-size:13px;color:var(--muted-foreground,#9ba6b3);margin:12px 0}.between{display:flex;justify-content:space-between;gap:10px;align-items:center}.full{width:100%}.nodeAddr{margin-top:10px}.empty{padding:15px 0;font-size:13px;color:var(--muted-foreground,#9ba6b3)}@media(max-width:550px){.stats{grid-template-columns:repeat(2,1fr)}nav button{font-size:13px;flex:1}.stat b{font-size:22px}.between{display:block}}
</style></head><body>
<p class="muted"><small>SkyrimSE 1.7.104.0 · original executable and shader bytes</small></p>
<p>Native image-space links and shipped equations now join the lighting-mod audits. Frame and input traces remain partial; live draw evidence is still open.</p>
<p class="note">The <a href="native-output-transfer.md">output-transfer report</a> and <a href="native-output-transfer.json">receipt catalog</a> trace one output-target-0 route through backbuffer view import, cached OM lookup and the Present receiver. Complete pixel transfer and numeric domains remain open; its overlapping evidence has separate counts.</p>
<div class="stats" id="stats"></div>
<nav aria-label="Rendering map views"><button data-tab="mods">Mod evidence</button><button data-tab="objects">New native links</button><button data-tab="equations">Shipped equations</button><button class="active" data-tab="calls">Native calls</button><button data-tab="inputs">Input traces</button><button data-tab="shaders">Shader groups</button><button data-tab="gates">Capture gates</button></nav>
<section class="tab" id="mods" hidden><p class="note">Nine content-mod pages and six pinned source repositories. Mod behavior and author claims guide native queries; they do not establish vanilla values.</p><input id="mod-filter" placeholder="Filter Lux, fog, HDR, SSS, shadows…" aria-label="Filter mod evidence"><div class="scroll" id="mod-list"></div></section>
<section class="tab" id="objects" hidden><p class="note">Original-byte helper ownership and guarded transfers. Successful construction and the pinned package are prerequisites; none is an observed retail pass.</p><div class="scroll" id="object-list"></div></section>
<section class="tab" id="equations" hidden><p class="note">54 groups, 108 records, 1,821 executable instructions, 3,285 component equations and 159 samples. Complete component/control equations are in image-space-arithmetic.json; native producers, resource domains and active order remain open.</p><div class="scroll" id="equation-list"></div></section>
<section class="tab" id="calls"><p class="note">Choose a function to follow verified direct calls and tail jumps. Connections retain their execution conditions; this is not a universal frame sequence.</p><select id="node" aria-label="Native function"></select><div class="panel" id="calls-content"></div></section>
<section class="tab" id="inputs" hidden><input id="input-filter" placeholder="Filter 45 input domains" aria-label="Filter input domains"><p class="note">Expand a domain for individually graded producer/consumer connections. Static evidence and project behavior do not establish effective retail state.</p><div class="scroll" id="input-list"></div></section>
<section class="tab" id="shaders" hidden><input id="shader-filter" placeholder="Filter groups by ordinal or label" aria-label="Filter shader groups"><p class="note">All 135 group identities have native loader links, conditional on the pinned package supplying the opened resource. Program counts and interfaces do not establish selection, complete equations or execution. The 57 embedded occurrences are cataloged separately.</p><div class="scroll" id="shader-list"></div></section>
<section class="tab" id="gates" hidden><p class="note">The 21 frame domains below have explicit observation requirements. Fiji's executable matches; startup and frame capture have not been verified.</p><div class="scroll" id="gate-list"></div></section>
<script>
const D=__PAYLOAD__;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nodes=Object.fromEntries(D.graph.nodes.map(n=>[n.id,n]));
const label=s=>String(s).replaceAll('_',' ');
const tag=s=>'<span class="tag '+(s==='open'?'open':'static')+'">'+esc(label(s))+'</span>';
const nums=[['124','native effect-slot links'],['54','groups with full equations'],[D.coverage.native_aggregate?.independently_decoded_unique_functions??'—','native functions decoded'],['0','retail frame captures']];
$('stats').innerHTML=nums.map(([n,s])=>'<div class="stat"><b>'+esc(n)+'</b><span>'+esc(s)+'</span></div>').join('');
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));});
$('node').innerHTML=D.graph.nodes.map(n=>'<option value="'+esc(n.id)+'">'+esc(n.meaning)+'</option>').join('');
function showNode(){const id=$('node').value,n=nodes[id],edges=D.graph.edges.filter(e=>e.source===id);let content='<h3>'+esc(n.meaning)+'</h3><p><code>'+esc(n.va)+'</code> '+tag(n.proof_status)+'</p>';
if(edges.length) content+=edges.map(e=>'<div class="edge"><button data-target="'+esc(e.target)+'">→ '+esc(nodes[e.target].meaning)+' <code>'+esc(nodes[e.target].va)+'</code></button><div><code>'+esc(e.callsite)+'</code></div><p class="note">'+esc(e.execution_condition)+'</p></div>').join('');else content+='<p class="empty">No outgoing direct edge is curated here. Indirect callbacks and broader call closure remain separate work.</p>';
const apis=D.api.filter(a=>a.function?.toLowerCase()===n.va?.toLowerCase());content+=apis.map(a=>'<div class="edge"><h3>'+esc(a.name)+'</h3><code>'+esc(a.callsite)+'</code><p class="note">'+esc(a.receiver_proof||a.proof||'See the byte-checked API boundary in frame-topology.json.')+'</p></div>').join('');
$('calls-content').innerHTML=content;$('calls-content').querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{$('node').value=b.dataset.target;showNode();});}
$('node').onchange=showNode;showNode();
function showInputs(){const q=$('input-filter').value.toLowerCase(),contracts=D.contracts.filter(c=>(c.id+' '+c.domain+' '+c.authored_or_runtime_inputs.join(' ')).toLowerCase().includes(q));$('input-list').innerHTML=contracts.map(c=>'<details><summary><code>'+esc(c.id)+'</code> '+esc(c.domain)+' '+tag('open')+'</summary>'+c.connections.map(e=>'<div class="edge">'+tag(e.status)+' <code>'+esc(e.id)+'</code><p><strong>'+esc(e.producer)+'</strong> → '+esc(e.consumer)+'</p><p>'+esc(e.claim)+'</p><small>Evidence: '+esc(e.evidence_ids.join(', ')||'not attached')+'</small></div>').join('')+'<p><strong>Remaining:</strong> '+esc(c.remaining_gates.join(' '))+'</p></details>').join('')||'<p class="empty">No matching domain.</p>';}
$('input-filter').oninput=showInputs;showInputs();
function showShaders(){const q=$('shader-filter').value.toLowerCase();$('shader-list').innerHTML=D.groups.filter(g=>(g.id+' '+(g.label||'unnamed')).toLowerCase().includes(q)).map(g=>'<details><summary><code>'+esc(g.id)+'</code> '+esc(g.label||'Unnamed')+'</summary><p>'+tag(g.label_status)+'</p><p>'+esc(Object.entries(g.program_counts).map(([stage,count])=>stage.toUpperCase()+': '+count).join(' · '))+'</p><small>Package region: '+esc(g.package_start)+'–'+esc(g.package_end)+' bytes</small><p class="note">The native constructor and ordered loader establish this group identity under the pinned package condition. Active resource resolution, shader selection and draw state remain unobserved.</p></details>').join('')||'<p class="empty">No matching group.</p>';}
$('shader-filter').oninput=showShaders;showShaders();
$('gate-list').innerHTML=D.stages.map(s=>'<details><summary>'+esc(label(s.stage))+' '+tag('open')+'</summary><p><strong>Static:</strong> '+esc(s.static_status)+'</p><p><strong>Needed:</strong> '+esc(s.needed_for_runtime_closure)+'</p><code>'+esc(s.native_anchor)+'</code></details>').join('');
function showMods(){const q=$('mod-filter').value.toLowerCase();let parts=[];
for(const f of D.content_findings){if(!(f.id+' '+f.claim+' '+f.scope+' '+f.unproved).toLowerCase().includes(q))continue;parts.push('<details class="mod-finding"><summary><code>'+esc(f.id)+'</code> '+esc(D.content_sources.find(s=>s.url===f.primary_source_url)?.title||'Author claim')+' · '+esc(f.claim)+'</summary><p>'+tag('author documented')+'</p><p>'+esc(f.scope)+'</p><p><strong>Open:</strong> '+esc(f.unproved)+'</p><p><a href="'+esc(f.primary_source_url)+'" target="_blank" rel="noreferrer">Author source</a> · <code>'+esc(f.query_ids.join(', '))+'</code></p></details>');}
for(const i of D.interventions){if(!(i.id+' '+i.title+' '+i.behavior+' '+i.scheduling).toLowerCase().includes(q))continue;parts.push('<details class="mod-intervention"><summary><code>'+esc(i.id)+'</code> '+esc(i.title)+'</summary><p>'+tag('pinned mod source')+'</p><p>'+esc(i.behavior)+'</p><p><strong>Schedule:</strong> '+esc(i.scheduling)+'</p><p><strong>Limits:</strong> '+esc(i.limits.join(' '))+'</p><p>'+i.source_anchors.map(id=>'<a href="'+esc(D.source_anchors[id].url)+'" target="_blank" rel="noreferrer">'+esc(id)+'</a>').join(' · ')+'</p><code>'+esc(i.next_native_query_ids.join(', '))+'</code></details>');}
if(!q){parts.push('<details><summary>Version pins and source conflicts</summary>'+D.content_sources.map(s=>'<p><a href="'+esc(s.url)+'" target="_blank" rel="noreferrer">'+esc(s.title)+'</a> · '+esc(s.page_version||'file listing')+'</p>').join('')+D.source_repos.map(r=>'<p><a href="'+esc(r.url.replace(/\\.git$/,''))+'" target="_blank" rel="noreferrer">'+esc(r.id)+'</a><br><code>'+esc(r.commit)+'</code></p>').join('')+D.source_conflicts.map(c=>'<p><strong>'+esc(c.claim)+'</strong><br>'+esc(c.native_implication)+'</p>').join('')+'</details>');}
$('mod-list').innerHTML=parts.join('')||'<p class="empty">No matching finding.</p>';}
$('mod-filter').oninput=showMods;showMods();
$('object-list').innerHTML=D.helpers.map(h=>'<details class="helper"><summary>Manager <code>'+esc(h.offset)+'</code> · '+h.fields.length+' shader fields</summary><p>Constructor <code>'+esc(h.constructor)+'</code>; renderer <code>'+esc(h.render||'not curated here')+'</code></p>'+h.fields.map(f=>'<p><code>'+esc(f.offset)+'</code> → slot '+esc(f.slot)+' / '+esc(f.group)+' <strong>'+esc(f.label)+'</strong></p>').join('')+D.guard_notes.filter(g=>g.owner===h.offset).map(g=>'<p><strong>State:</strong> '+esc(g.condition||g.scope)+'; live value unknown.</p>').join('')+'</details>').join('')+'<details><summary>Compute API route and HDR child ownership</summary>'+D.compute.api_calls.map(a=>'<p><code>'+esc(a.instruction.instruction_va)+'</code> '+esc(a.method)+'<br>'+esc(a.arguments)+'</p>').join('')+'<p>HDR child '+esc(D.hdr.hdr_child_index)+' → slot '+esc(D.hdr.selected_effect_slot)+' '+esc(D.hdr.native_loader_label)+'. Parameter channel '+esc(D.hdr.parameter_channel)+' receives '+esc(D.hdr.byte_count)+' bytes at <code>'+esc(D.hdr.source_pointer)+'</code>; shader buffer-slot transfer remains open.</p><p>'+esc(D.hdr.open.join(' '))+'</p></details>'+'<details><summary>Ten checked direct transfers</summary>'+D.transfers.map(e=>'<p><code>'+esc(e.callsite)+'</code> → <code>'+esc(e.target)+'</code><br>'+esc(e.condition)+'<br>'+esc(e.data)+'</p>').join('')+'</details>';
$('equation-list').innerHTML=Object.entries(D.arithmetic_families).map(([name,c])=>'<details><summary>'+esc(label(name))+' '+tag('shipped arithmetic')+'</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.5">'+esc(JSON.stringify(c,null,2))+'</pre><p class="note">Input meanings and selected resource/view state remain open.</p></details>').join('');
function assert(v,m){if(!v)throw new Error(m);} $('node').value='manager';showNode();assert($('calls-content').querySelectorAll('[data-target]').length===3,'Manager call edges');$('node').value='frame';showNode();$('shader-filter').value='group-006';showShaders();assert($('shader-list').querySelectorAll('details').length===1,'Shader filter');$('shader-filter').value='';showShaders();$('input-filter').value='I-C13';showInputs();assert($('input-list').querySelectorAll('details').length===1,'Input filter');$('input-filter').value='';showInputs();assert($('object-list').querySelectorAll('.helper').length===8,'Native helper coverage');assert($('mod-list').querySelectorAll('.mod-intervention').length===22,'Source intervention coverage');$('mod-filter').value='fog';showMods();assert($('mod-list').querySelectorAll('details').length>0,'Mod filter');$('mod-filter').value='';showMods();document.querySelector('[data-tab=equations]').click();assert(!$('equations').hidden&&$('mods').hidden,'Equation tab routing');document.querySelector('[data-tab=mods]').click();console.log(JSON.stringify({interactionChecks:'passed',nativeNodes:D.graph.nodes.length,directEdges:D.graph.edges.length,inputDomains:D.contracts.length,shaderGroups:D.groups.length,nativeHelpers:D.helpers.length,sourceInterventions:D.interventions.length,captureGates:D.stages.length,runtimeCaptures:0}));
</script></body></html>'''.replace('__PAYLOAD__',payload)
(folder/'map.html').write_text(html)
print(json.dumps({'path':str(folder/'map.html'),'bytes':len(html.encode()),'nodes':len(data['graph']['nodes']),'domains':len(data['contracts']),'groups':len(data['groups'])}))
