pub mod app;
mod capture_frame;
pub mod cell_commands;
pub mod color_pipeline;
pub mod config;
pub mod console;
pub mod door_crossing;
pub mod doors;
pub mod indirect_metrics;
mod interaction;
pub mod lights;
mod matched_route;
pub mod mesh_preparation_retry;
pub mod metrics;
pub mod nif_depth;
pub mod nif_material;
pub mod pacing;
pub mod papyrus_runtime;
pub mod physics;
pub mod prepass_vertex_alpha;
pub mod profiling;
pub mod render;
pub mod render_timing;
mod renderer_init;
mod scene_evidence;
pub mod schedule_timing;
pub mod shots;
pub mod sky;
pub mod skyrim_ini;
pub mod streaming;
mod streaming_gpu_metrics;
mod streaming_preparation;
mod streaming_trace;
pub mod terrain_upload;
pub mod visibility_optimization;
pub mod world;

pub use app::run;

mod mesh_residency_audit;
